# Generated by Django 4.1.2 on 2022-10-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='day_birth',
            field=models.DateField(default='', verbose_name='Birth date'),
        ),
    ]
