# Generated by Django 4.1.2 on 2022-10-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_courseteacher_day_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='courses',
            new_name='course',
        ),
    ]
