# Generated by Django 4.1.2 on 2022-11-23 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursefeedback',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
